CREATE TABLE IF NOT EXISTS anomaly_events (
    id SERIAL PRIMARY KEY,
    device TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    metric_name TEXT NOT NULL,
    metric_value REAL,
    detector_type TEXT NOT NULL,
    anomaly_score REAL,
    severity TEXT,
    is_anomaly INTEGER,
    details TEXT,
    source_file TEXT,
    ingest_run_id TEXT,
    workload_pattern TEXT,
    root_cause_hint TEXT,
    util_pct REAL,
    aqu_sz REAL,
    avg_latency_ms REAL,
    read_ratio REAL,
    write_ratio REAL,
    avg_request_size_kb REAL,
    total_iops REAL,
    total_throughput_mb_s REAL,
    saturation_score REAL,
    latency_pressure REAL
);
